add_library(tttracy SHARED tracyshim.cpp ${CMAKE_SOURCE_DIR}/third_party/tracy/public/TracyClient.cpp)
target_compile_definitions(tttracy PRIVATE TTPLAYER_TRACY TRACY_ENABLE)
target_include_directories(tttracy PRIVATE ${CMAKE_SOURCE_DIR}/third_party/tracy/public)
set_target_properties(tttracy PROPERTIES PREFIX "")
if (MSVC)
    set_property(TARGET tttracy PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
endif()

add_executable(tttracy_test EXCLUDE_FROM_ALL tracyshim.cpp tests/tracyshim_test.cpp)
target_compile_definitions(tttracy_test PRIVATE TRACY_ENABLE)
target_include_directories(tttracy_test PRIVATE ${CMAKE_SOURCE_DIR}/third_party/tracy/public)
